// product
export const GET_DATA_PRODUCT_REQUEST = 'GET_DATA_PRODUCT_REQUEST';
export const GET_DATA_PRODUCT_SUCCESS = 'GET_DATA_PRODUCT_SUCCESS';
export const GET_DATA_PRODUCT_FAILD = 'GET_DATA_PRODUCT_FAILD';

export const GET_DATA_SLIDER_REQUEST = 'GET_DATA_SLIDER_REQUEST';
export const GET_DATA_SLIDER_SUCCESS = 'GET_DATA_SLIDER_SUCCESS';
export const GET_DATA_SLIDER_FAILD = 'GET_DATA_SLIDER_FAILD';

export const GET_DATA_PRODUCT_DETAIL_REQUEST = 'GET_DATA_PRODUCT_DETAIL_REQUEST';
export const GET_DATA_PRODUCT_DETAIL_SUCCESS = 'GET_DATA_PRODUCT_DETAIL_SUCCESS';
export const GET_DATA_PRODUCT_DETAIL_FAILD = 'GET_DATA_PRODUCT_DETAIL_FAILD';
