// product
export const GET_DATA_PRODUCT_REQUEST = '@@redux/home/GET_DATA_PRODUCT_REQUEST';
export const GET_DATA_PRODUCT_SUCCESS = '@@redux/home/GET_DATA_PRODUCT_SUCCESS';
export const GET_DATA_PRODUCT_FAILD = '@@redux/home/GET_DATA_PRODUCT_FAILD';

export const GET_DATA_SLIDER_REQUEST = '@@redux/home/GET_DATA_SLIDER_REQUEST';
export const GET_DATA_SLIDER_SUCCESS = '@@redux/home/GET_DATA_SLIDER_SUCCESS';
export const GET_DATA_SLIDER_FAILD = '@@redux/home/GET_DATA_SLIDER_FAILD';

export const GET_DATA_PRODUCT_DETAIL_REQUEST = '@@redux/detail/GET_DATA_PRODUCT_DETAIL_REQUEST';
export const GET_DATA_PRODUCT_DETAIL_SUCCESS = '@@redux/detail/GET_DATA_PRODUCT_DETAIL_SUCCESS';
export const GET_DATA_PRODUCT_DETAIL_FAILD = '@@redux/detail/GET_DATA_PRODUCT_DETAIL_FAILD';
