export const NEWS_NOTIFICATION_REQUEST = '@@redux/product/NEWS_DETAIL_NOTIFICATION_REQUEST';
export const NEWS_NOTIFICATION_SUCCESS = '@@redux/product/NEWS_DETAIL_NOTIFICATION_SUCCESS';
export const NEWS_NOTIFICATION_FAILED = '@@redux/product/NEWS_DETAIL_NOTIFICATION_FAILED';
