// product
export const PRODUCT_GET_DATA_PRODUCT_REQUEST = '@@redux/product/GET_DATA_PRODUCT_REQUEST';
export const PRODUCT_GET_DATA_PRODUCT_SUCCESS = '@@redux/product/GET_DATA_PRODUCT_SUCCESS';
export const PRODUCT_GET_DATA_PRODUCT_FAILD = '@@redux/product/GET_DATA_PRODUCT_FAILD';

// search product
export const SEARCH_DATA_PRODUCT_REQUEST = '@@redux/product/SEARCH_DATA_PRODUCT_REQUEST';
export const SEARCH_DATA_PRODUCT_SUCCESS = '@@redux/product/SEARCH_DATA_PRODUCT_SUCCESS';
export const SEARCH_DATA_PRODUCT_FAILED = '@@redux/product/SEARCH_DATA_PRODUCT_FAILED';

// search product
export const LOADMORE_SEARCH_DATA_PRODUCT_REQUEST = '@@redux/product/LOADMORE_SEARCH_DATA_PRODUCT_REQUEST';
export const LOADMORE_SEARCH_DATA_PRODUCT_SUCCESS = '@@redux/product/LOADMORE_SEARCH_DATA_PRODUCT_SUCCESS';
export const LOADMORE_SEARCH_DATA_PRODUCT_FAILED = '@@redux/product/LOADMORE_SEARCH_DATA_PRODUCT_FAILED';

export const SET_CHOICED_IMAGE = '@@redux/product/SET_CHOICED_IMAGE';
