// qrcode
export const GET_DATA_SCAN_REQUEST = '@@redux/qr/GET_DATA_SCAN_REQUEST';
export const GET_DATA_SCAN_SUCCESS = '@@redux/qr/GET_DATA_SCAN_SUCCESS';
export const GET_DATA_SCAN_FAILD = '@@redux/qr/GET_DATA_SCAN_FAILD';

export const VERIFY_PRODUCT_REQUEST = '@@redux/qr/VERIFY_PRODUCT_REQUEST';
export const VERIFY_PRODUCT_SUCCESS = '@@redux/qr/VERIFY_PRODUCT_SUCCESS';
export const VERIFY_PRODUCT_FAILED = '@@redux/qr/VERIFY_PRODUCT_FAILED';

export const ACTIVE_PRODUCT_REQUEST = '@@redux/qr/ACTIVE_PRODUCT_REQUEST';
export const ACTIVE_PRODUCT_SUCCESS = '@@redux/qr/ACTIVE_PRODUCT_SUCCESS';
export const ACTIVE_PRODUCT_FAILED = '@@redux/qr/ACTIVE_PRODUCT_FAILED';

export const CHANGE_INPUT_VERIFY = '@@redux/qr/CHANGE_INPUT_VERIFY';
