export const CHECKIN_CHECKOUT_REQUEST = '@@redux/timekeep/CHECKIN_CHECKOUT_REQUEST';
export const CHECKIN_CHECKOUT_SUCCESS = '@@redux/timekeep/CHECKIN_CHECKOUT_SUCCESS';
export const CHECKIN_CHECKOUT_FAILED = '@@redux/timekeep/CHECKIN_CHECKOUT_FAILED';

export const WORKOUT_REGISTER_REQUEST = '@@redux/timekeep/WORKOUT_REGISTER_REQUEST';
export const WORKOUT_REGISTER_SUCCESS = '@@redux/timekeep/WORKOUT_REGISTER_SUCCESS';
export const WORKOUT_REGISTER_FAILED = '@@redux/timekeep/WORKOUT_REGISTER_FAILED';
