const screens = {
  walkthrough: 'WalkThrough',
  home: 'Home',
  homeDetail: 'HomeDetail',
  homeMore: 'HomeMore',
  notification: 'Notification',
  tabqrcode: 'TabQRCode',
  qrcode: 'QRCode',
  news: 'News',
  newsDetail: 'NewsDetail',
  profile: 'Profile',
  authStack: 'AuthStack',
  appStack: 'AppStack',
  drawerStack: 'DrawerStack',
  bottomTabStack: 'BottomTabStack',
  login: 'Login',
  register: 'Register',
  TabMain: 'TabMain',
  product: 'Product',
  product_detail: 'ProductDetail',
  product_scan: 'ProductScan',
  settingMessageScreen: 'SettingMessageScreen',
  buyHistoryScreen: 'BuyHistoryScreen',
  ruleScreen: 'RuleScreen',
  tutorialScreen: 'TutorialScreen',
  contactScreen: 'ContactScreen',
  requestCodeScreen: 'RequestCodeScreen',
  managerRequestCodeScreen: 'ManagerRequestCodeScreen',
  historyScanCode: 'HistoryScanCode',
  changeInfo: 'ChangeInfo',
  rules: 'Rules',
};

enum ROUTES {
  walkthrough = 'WalkThrough',
  home = 'Home',
  homeDetail = 'HomeDetail',
  homeMore = 'HomeMore',
  notification = 'Notification',
  tabqrcode = 'TabQRCode',
  qrcode = 'QRCode',
  news = 'News',
  profile = 'Profile',
  authStack = 'AuthStack',
  appStack = 'AppStack',
  drawerStack = 'DrawerStack',
  bottomTabStack = 'BottomTabStack',
  login = 'Login',
  register = 'Register',
  TabMain = 'TabMain',
  product = 'Product',
  product_detail = 'ProductDetail',
  settingMessageScreen = 'SettingMessageScreen',
  buyHistoryScreen = 'BuyHistoryScreen',
  ruleScreen = 'RuleScreen',
  tutorialScreen = 'TutorialScreen',
  contactScreen = 'ContactScreen',
  requestCodeScreen = 'RequestCodeScreen',
  managerRequestCodeScreen = 'ManagerRequestCodeScreen',
  historyScanCode = 'HistoryScanCode',
  changeInfo = 'ChangeInfo',
  rules = 'Rules',
}

export { screens, ROUTES };
