export enum BACKGROUND_TYPE {
  GREEN_GRADIENT = 'GREEN_GRADIENT',
  NORMAL_BACKGROUND = 'NORMAL_BACKGROUND',
  MINT_BLUE_GRADIENT = 'MINT_BLUE_GRADIENT',
}

export interface BackgroundProps {
  type: string;
}
